require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'TypeScriptAppNativeBase' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  permissions_path = '../node_modules/react-native-permissions/ios'
  
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
    pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
    pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

  pod 'react-native-pager-view', :path => '../node_modules/react-native-pager-view'

  pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'aliyun-oss-react-native-self', :path => '../node_modules/aliyun-oss-react-native-self'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  pod 'RCTAliyunPush', :path => '../node_modules/react-native-aliyun-push'

  pod 'RNAlipay', :path => '../node_modules/react-native-alipay-latest/ios'

  pod 'RNIap', :path => '../node_modules/react-native-iap'

  pod 'react-native-wechat', :path => '../node_modules/@shm-open/react-native-wechat'

  pod 'Bugly'

  target 'TypeScriptAppNativeBaseTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end
